# Generated by Django 6.0.4 on 2026-04-23 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Horse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=50, unique=True)),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('color', models.CharField(blank=True, max_length=50)),
                ('vin_number', models.CharField(blank=True, max_length=100)),
                ('license_expiry', models.DateField()),
                ('insurance_expiry', models.DateField()),
                ('roadworthy_expiry', models.DateField(blank=True, null=True)),
                ('odometer', models.IntegerField(default=0)),
                ('service_interval_km', models.IntegerField(default=20000)),
                ('last_service_km', models.IntegerField(default=0)),
                ('next_service_km', models.IntegerField(default=20000)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'In Maintenance')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('photo', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=50, unique=True)),
                ('trailer_type', models.CharField(choices=[('flatbed', 'Flatbed'), ('refrigerated', 'Refrigerated'), ('tanker', 'Tanker'), ('curtainsider', 'Curtainsider'), ('skeletal', 'Skeletal'), ('other', 'Other')], max_length=20)),
                ('make', models.CharField(blank=True, max_length=100)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('capacity_tons', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('license_expiry', models.DateField()),
                ('insurance_expiry', models.DateField()),
                ('roadworthy_expiry', models.DateField(blank=True, null=True)),
                ('odometer', models.IntegerField(default=0)),
                ('service_interval_km', models.IntegerField(default=20000)),
                ('last_service_km', models.IntegerField(default=0)),
                ('next_service_km', models.IntegerField(default=20000)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'In Maintenance')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('photo', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
