# Generated by Django 6.0.4 on 2026-04-23 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('minor', 'Minor Service'), ('major', 'Major Service'), ('oil_change', 'Oil Change'), ('brake', 'Brake Service'), ('clutch', 'Clutch'), ('gearbox', 'Gearbox'), ('diff', 'Differential'), ('electrical', 'Electrical'), ('body', 'Body Work'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('workshop_name', models.CharField(blank=True, max_length=200)),
                ('workshop_contact', models.CharField(blank=True, max_length=100)),
                ('technician', models.CharField(blank=True, max_length=100)),
                ('odometer_at_service', models.IntegerField()),
                ('next_service_km', models.IntegerField(blank=True, null=True)),
                ('parts_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('labour_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('scheduled_date', models.DateField()),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='scheduled', max_length=20)),
                ('document_url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('horse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='vehicles.horse')),
            ],
        ),
    ]
