# Generated by Django 6.0.4 on 2026-04-23 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tyre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('horse', 'Horse'), ('trailer', 'Trailer')], max_length=10)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('size', models.CharField(blank=True, max_length=50)),
                ('position', models.CharField(choices=[('steer_left', 'Steer Left'), ('steer_right', 'Steer Right'), ('drive_left_outer', 'Drive Left Outer'), ('drive_left_inner', 'Drive Left Inner'), ('drive_right_outer', 'Drive Right Outer'), ('drive_right_inner', 'Drive Right Inner'), ('trailer_1', 'Trailer Axle 1'), ('trailer_2', 'Trailer Axle 2'), ('trailer_3', 'Trailer Axle 3'), ('spare', 'Spare')], max_length=30)),
                ('installed_km', models.IntegerField()),
                ('replaced_km', models.IntegerField(blank=True, null=True)),
                ('km_lifespan', models.IntegerField(default=120000)),
                ('condition', models.CharField(choices=[('good', 'Good'), ('worn', 'Worn'), ('critical', 'Critical — Replace Soon'), ('replaced', 'Replaced')], default='good', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('horse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tyres', to='vehicles.horse')),
                ('trailer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tyres', to='vehicles.trailer')),
            ],
        ),
    ]
