# Generated by Django 6.0.1 on 2026-05-14 08:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips', '0002_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oil_level', models.BooleanField(default=False)),
                ('coolant_level', models.BooleanField(default=False)),
                ('no_engine_leaks', models.BooleanField(default=False)),
                ('tyre_pressure', models.BooleanField(default=False)),
                ('tyre_condition', models.BooleanField(default=False)),
                ('wheel_nuts', models.BooleanField(default=False)),
                ('brake_response', models.BooleanField(default=False)),
                ('air_pressure', models.BooleanField(default=False)),
                ('headlights', models.BooleanField(default=False)),
                ('indicators', models.BooleanField(default=False)),
                ('brake_lights', models.BooleanField(default=False)),
                ('fire_extinguisher', models.BooleanField(default=False)),
                ('reflective_triangles', models.BooleanField(default=False)),
                ('seatbelt', models.BooleanField(default=False)),
                ('trailer_tyres', models.BooleanField(default=False)),
                ('coupling_system', models.BooleanField(default=False)),
                ('trailer_lights', models.BooleanField(default=False)),
                ('cargo_locking', models.BooleanField(default=False)),
                ('trailer_suspension', models.BooleanField(default=False)),
                ('overall_status', models.CharField(choices=[('pass', 'Pass'), ('minor_issue', 'Minor Issue'), ('critical', 'Critical Issue')], default='pass', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('odometer', models.IntegerField(blank=True, null=True)),
                ('check_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(limit_choices_to={'role': 'driver'}, on_delete=django.db.models.deletion.PROTECT, related_name='daily_checks', to=settings.AUTH_USER_MODEL)),
                ('horse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_checks', to='vehicles.horse')),
                ('trailer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='daily_checks', to='vehicles.trailer')),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_checks', to='trips.trip')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
