# Generated by Django 6.0.4 on 2026-04-23 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200)),
                ('client_contact', models.CharField(blank=True, max_length=100)),
                ('client_phone', models.CharField(blank=True, max_length=20)),
                ('origin', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('cargo_description', models.TextField()),
                ('cargo_type', models.CharField(choices=[('general', 'General Freight'), ('perishable', 'Perishable'), ('hazardous', 'Hazardous'), ('oversized', 'Oversized'), ('bulk', 'Bulk'), ('other', 'Other')], default='general', max_length=20)),
                ('cargo_weight_tons', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('waybill_number', models.CharField(blank=True, max_length=100)),
                ('waybill_document', models.URLField(blank=True)),
                ('scheduled_start', models.DateTimeField()),
                ('scheduled_end', models.DateTimeField(blank=True, null=True)),
                ('actual_start', models.DateTimeField(blank=True, null=True)),
                ('actual_end', models.DateTimeField(blank=True, null=True)),
                ('start_odometer', models.IntegerField(blank=True, null=True)),
                ('end_odometer', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
