# Generated by Django 6.0.4 on 2026-04-23 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gps', '0001_initial'),
        ('trips', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gpslocation',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gps_locations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gpslocation',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gps_locations', to='trips.trip'),
        ),
        migrations.AddIndex(
            model_name='gpslocation',
            index=models.Index(fields=['trip', 'timestamp'], name='gps_gpsloca_trip_id_6b2a62_idx'),
        ),
    ]
