# Generated by Django 6.0.4 on 2026-04-23 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('invoice_type', models.CharField(choices=[('receivable', 'Receivable — Client owes us'), ('payable', 'Payable — We owe supplier')], max_length=15)),
                ('category', models.CharField(choices=[('trip', 'Trip / Freight'), ('fuel', 'Fuel'), ('service', 'Vehicle Service'), ('repair', 'Repair'), ('tyre', 'Tyres'), ('other', 'Other')], default='trip', max_length=10)),
                ('party_name', models.CharField(max_length=200)),
                ('party_email', models.EmailField(blank=True, max_length=254)),
                ('party_phone', models.CharField(blank=True, max_length=20)),
                ('party_address', models.TextField(blank=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_percent', models.DecimalField(decimal_places=2, default=15, max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('issue_date', models.DateField()),
                ('due_date', models.DateField()),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='draft', max_length=15)),
                ('document_url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
