# Generated by Django 6.0.4 on 2026-05-26 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My Fleet Company', max_length=200)),
                ('reg_no', models.CharField(blank=True, max_length=50)),
                ('vat_no', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('bank_acc', models.CharField(blank=True, max_length=50)),
                ('bank_branch', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Company Profile',
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='party_vat',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='invoice',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='truck_reg',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
