# Generated by Django 6.0.4 on 2026-05-27 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_companyprofile_invoice_description_invoice_party_vat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='contact_person',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
