# Generated by Django 6.0.4 on 2026-04-23 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fuel', '0001_initial'),
        ('trips', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelentry',
            name='entered_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fuel_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fuelentry',
            name='horse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fuel_entries', to='vehicles.horse'),
        ),
        migrations.AddField(
            model_name='fuelentry',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_entries', to='trips.trip'),
        ),
    ]
